export const SPELL_CATEGORIES = [
  {value: -99, label: "NPC"},
  {value: -1, label: " AA Procs"},
  {value: 1, label: "Direct Damage [Magic]"},
  {value: 2, label: "Direct Damage [Undead]"},
  {value: 3, label: "Direct Damage [Summoned]"},
  {value: 4, label: "Direct Damage [Life Taps]"},
  {value: 5, label: "Direct Damage [Plant]"},
  {value: 6, label: "Direct Damage [Velious Races]"},
  {value: 7, label: "Damage over Time [Magic]"},
  {value: 8, label: "Damage over Time [Undead]"},
  {value: 9, label: "Damage over Time [Life Taps]"},
  {value: 10, label: "Targeted Area of Effect Damage"},
  {value: 11, label: "Point Blank Area of Effect Damage"},
  {value: 12, label: "Area of Effect Rain"},
  {value: 13, label: "Direct Damage [Bolt]"},
  {value: 14, label: "Stun [Targeted Area of Effect]"},
  {value: 15, label: "Stun [Targeted]"},
  {value: 16, label: "Stun [Point Blank Area of Effect]"},
  {value: 17, label: "Drains [Health/Mana]"},
  {value: 18, label: "Drains [Stats]"},
  {value: 19, label: "Contact Innates"},
  {value: 20, label: "Heal [Instant]"},
  {value: 21, label: "Heal [Duration]"},
  {value: 22, label: "Group Heal [Instant]"},
  {value: 23, label: "Group Heal [Duration]"},
  {value: 24, label: "Regeneration [Single]"},
  {value: 25, label: "Regeneration [Group]"},
  {value: 26, label: "Heal [Own Pet]"},
  {value: 27, label: "Resurrect"},
  {value: 28, label: "Necromancer Life Transfer"},
  {value: 29, label: "Cure [Poison]"},
  {value: 30, label: "Health Buffs [Single]"},
  {value: 32, label: "AC Buff [Single]"},
  {value: 34, label: "Hate Mod Buffs"},
  {value: 35, label: "Haste [Single]"},
  {value: 36, label: "Haste [Pet]"},
  {value: 37, label: "Haste [Group]"},
  {value: 38, label: "Slow [Single]"},
  {value: 39, label: "Slow [Targeted Area]"},
  {value: 40, label: "Cannabalize"},
  {value: 41, label: "Move Speed [Single]"},
  {value: 42, label: "Move Speed [Group]"},
  {value: 43, label: "Wolf Form"},
  {value: 44, label: "Move Speed [Pet]"},
  {value: 45, label: "Illusion [Self]"},
  {value: 46, label: "Lich"},
  {value: 47, label: "Bear Form"},
  {value: 48, label: "Tree Form"},
  {value: 49, label: "Dead Man Floating"},
  {value: 50, label: "Root"},
  {value: 51, label: "Summon Pet"},
  {value: 52, label: "Summon Corpse"},
  {value: 53, label: "Sense Undead"},
  {value: 54, label: "Invulnerability"},
  {value: 55, label: "Gate [Combat Portal]"},
  {value: 56, label: "Gate [Self Gates]"},
  {value: 58, label: "Translocate"},
  {value: 59, label: "Shadow Step"},
  {value: 60, label: "Enchant Item"},
  {value: 61, label: "Summon [Misc Item]"},
  {value: 62, label: "Fear"},
  {value: 63, label: "Fear [Animal]"},
  {value: 64, label: "Fear [Undead]"},
  {value: 65, label: "Damage Shield [Single]"},
  {value: 66, label: "Damage Shield [Group]"},
  {value: 67, label: "Mark Of Karn"},
  {value: 68, label: "Damage Shield [Self]"},
  {value: 69, label: "Resist Debuffs"},
  {value: 70, label: "Resist Buffs"},
  {value: 71, label: "BST Pet Buffs"},
  {value: 72, label: "Summon Familiar"},
  {value: 73, label: "STR Buff"},
  {value: 74, label: "DEX Buff"},
  {value: 75, label: "AGI Buff"},
  {value: 76, label: "STA Buff"},
  {value: 77, label: "INT Buff"},
  {value: 78, label: "CHA Buff"},
  {value: 79, label: "Stat Debuffs"},
  {value: 80, label: "Invisible Undead"},
  {value: 81, label: "Invisible Animals"},
  {value: 82, label: "Invisibility"},
  {value: 83, label: "Absorb Damage"},
  {value: 84, label: "Casting Level Buffs"},
  {value: 85, label: "Clarity Line"},
  {value: 86, label: "Max Mana Buffs"},
  {value: 87, label: "Drain Mana"},
  {value: 88, label: "Mana Transfer"},
  {value: 89, label: "Instant Gain Mana"},
  {value: 90, label: "Lower Hate [Jolt]"},
  {value: 91, label: "Increase Archery"},
  {value: 92, label: "Attack Buff"},
  {value: 93, label: "Vision"},
  {value: 94, label: "Water Breathing"},
  {value: 95, label: "Improve Faction"},
  {value: 96, label: "Charm"},
  {value: 97, label: "Dispell"},
  {value: 98, label: "Lull"},
  {value: 99, label: "Mesmerise"},
  {value: 100, label: "Spell Focus Items"},
  {value: 101, label: "Snare [single]"},
  {value: 102, label: "Snare [Area of Effect]"},
  {value: 105, label: "Feign Death"},
  {value: 106, label: "Identify"},
  {value: 107, label: "Reclaim Energy"},
  {value: 108, label: "Find Corpse"},
  {value: 109, label: "Summon Player"},
  {value: 110, label: "Spell Shield"},
  {value: 112, label: "Blindness"},
  {value: 113, label: "Levitation"},
  {value: 114, label: "Extinguish Fatigue"},
  {value: 115, label: "Death Pact"},
  {value: 116, label: "Memory Blur"},
  {value: 118, label: "Height"},
  {value: 119, label: "Add Hate"},
  {value: 120, label: "Iron Maiden"},
  {value: 121, label: "Focus Spells"},
  {value: 122, label: "Melee Guard"},
  {value: 125, label: "Direct Damage [Fire]"},
  {value: 126, label: "Direct Damage [Ice]"},
  {value: 127, label: "Direct Damage [Poison]"},
  {value: 128, label: "Direct Damage [Disease]"},
  {value: 129, label: "Damage over Time [Fire]"},
  {value: 130, label: "Damage over Time [Ice]"},
  {value: 131, label: "Damage over Time [Poison]"},
  {value: 132, label: "Damage over Time [Disease]"},
  {value: 133, label: "INT Caster Chest Opening"},
  {value: 134, label: "INT Caster Chest Trap Appraisal"},
  {value: 135, label: "INT Caster Chest Trap Disarm"},
  {value: 136, label: "WIS Caster Chest Trap Disarm"},
  {value: 137, label: "WIS Caster Chest Trap Appraisal"},
  {value: 138, label: "WIS Caster Chest Opening"},
  {value: 140, label: "Destroy [Undead]"},
  {value: 141, label: "Destroy [Summoned]"},
  {value: 142, label: "Targeted Area of Effect [Fire]"},
  {value: 143, label: "Targeted Area of Effect [Ice]"},
  {value: 146, label: "Point Blank Area of Effect [Fire]"},
  {value: 147, label: "Point Blank Area of Effect [Ice]"},
  {value: 150, label: "Rain [Fire]"},
  {value: 151, label: "Rain [Ice]"},
  {value: 152, label: "Rain [Poison]"},
  {value: 154, label: "Fear Song"},
  {value: 155, label: "Fast Heals"},
  {value: 156, label: "Mana to Health"},
  {value: 157, label: "Pet Siphons"},
  {value: 159, label: "Cure [Disease]"},
  {value: 160, label: "Cure [Curse]"},
  {value: 161, label: "Cure [Multiple]"},
  {value: 162, label: "Cure [Blind]"},
  {value: 163, label: "Group Cure [Multiple]"},
  {value: 164, label: "Misc Effects"},
  {value: 165, label: "Shielding"},
  {value: 166, label: "PAL/RNG/BST Health Buffs"},
  {value: 167, label: "Symbols"},
  {value: 168, label: "Aegolism Line"},
  {value: 169, label: "Paladin AC Buffs"},
  {value: 170, label: "Spell Damage Mitigate"},
  {value: 171, label: "Spell/Melee Block"},
  {value: 172, label: "Spell Reflect"},
  {value: 173, label: "Hybrid AC Buffs"},
  {value: 174, label: "Health/Mana Regeneration"},
  {value: 175, label: "Aggro Decreasers"},
  {value: 200, label: "Misc Spells"},
  {value: 201, label: "Disciplines"},
  {value: 202, label: "Melee Haste"},
  {value: 203, label: "Area of Effect Slow"},
  {value: 204, label: "Summon Air Pet"},
  {value: 205, label: "Summon Water Pet"},
  {value: 206, label: "Summon Fire Pet"},
  {value: 207, label: "Summon Earth Pet"},
  {value: 208, label: "Summon Monster Pet"},
  {value: 209, label: "Transport [Antonica]"},
  {value: 210, label: "Transport [Odus]"},
  {value: 211, label: "Transport [Faydwer]"},
  {value: 212, label: "Transport [Kunark]"},
  {value: 213, label: "Transport [Velious]"},
  {value: 214, label: "Transport [Luclin]"},
  {value: 215, label: "Transport [Planes]"},
  {value: 216, label: "Transport [Gates/Omens]"},
  {value: 217, label: "Summon [Weapon]"},
  {value: 218, label: "Summon [Focus]"},
  {value: 219, label: "Summon [Food/Drink]"},
  {value: 220, label: "Summon [Armor]"},
  {value: 999, label: "AA / Abilities"}
];

export const SPELL_GROUPS = [
  {value: -99, label: "NPC"},
  {value: -1, label: "AA Procs"},
  {value: 1, label: "Direct Damage [Magic]"},
  {value: 2, label: "Direct Damage [Undead]"},
  {value: 3, label: "Direct Damage [Summoned]"},
  {value: 4, label: "Direct Damage [Life Taps]"},
  {value: 5, label: "Direct Damage [Plant]"},
  {value: 6, label: "Direct Damage [Velious Races]"},
  {value: 7, label: "Damage over Time [Magic]"},
  {value: 8, label: "Damage over Time [Undead]"},
  {value: 9, label: "Damage over Time [Life Taps]"},
  {value: 10, label: "Targeted Area of Effect Damage"},
  {value: 11, label: "Point Blank Area of Effect Damage"},
  {value: 12, label: "Area of Effect Rain"},
  {value: 13, label: "Direct Damage [Bolt]"},
  {value: 14, label: "Stun [Targeted Area of Effect]"},
  {value: 15, label: "Stun [Targeted]"},
  {value: 16, label: "Stun [Point Blank Area of Effect]"},
  {value: 17, label: "Drains [Health/Mana]"},
  {value: 18, label: "Drains [Stats]"},
  {value: 19, label: "Contact Innates"},
  {value: 20, label: "Heal [Instant]"},
  {value: 21, label: "Heal [Duration]"},
  {value: 22, label: "Group Heal [Instant]"},
  {value: 23, label: "Group Heal [Duration]"},
  {value: 24, label: "Regeneration [Single]"},
  {value: 25, label: "Regeneration [Group]"},
  {value: 26, label: "Heal [Own Pet]"},
  {value: 27, label: "Resurrect"},
  {value: 28, label: "Necromancer Life Transfer"},
  {value: 29, label: "Cure [Poison]"},
  {value: 30, label: "Health Buffs [Single]"},
  {value: 32, label: "AC Buff [Single]"},
  {value: 34, label: "Hate Mod Buffs"},
  {value: 35, label: "Haste [Single]"},
  {value: 36, label: "Haste [Pet]"},
  {value: 37, label: "Haste [Group]"},
  {value: 38, label: "Slow [Single]"},
  {value: 39, label: "Slow [Targeted Area]"},
  {value: 40, label: "Cannabalize"},
  {value: 41, label: "Move Speed [Single]"},
  {value: 42, label: "Move Speed [Group]"},
  {value: 43, label: "Wolf Form"},
  {value: 44, label: "Move Speed [Pet]"},
  {value: 45, label: "Illusion [Self]"},
  {value: 46, label: "Lich"},
  {value: 47, label: "Bear Form"},
  {value: 48, label: "Tree Form"},
  {value: 49, label: "Dead Man Floating"},
  {value: 50, label: "Root"},
  {value: 51, label: "Summon Pet"},
  {value: 52, label: "Summon Corpse"},
  {value: 53, label: "Sense Undead"},
  {value: 54, label: "Invulnerability"},
  {value: 55, label: "Gate [Combat Portal]"},
  {value: 56, label: "Gate [Self Gates]"},
  {value: 58, label: "Translocate"},
  {value: 59, label: "Shadow Step"},
  {value: 60, label: "Enchant Item"},
  {value: 61, label: "Summon [Misc Item]"},
  {value: 62, label: "Fear"},
  {value: 63, label: "Fear [Animal]"},
  {value: 64, label: "Fear [Undead]"},
  {value: 65, label: "Damage Shield [Single]"},
  {value: 66, label: "Damage Shield [Group]"},
  {value: 67, label: "Mark Of Karn"},
  {value: 68, label: "Damage Shield [Self]"},
  {value: 69, label: "Resist Debuffs"},
  {value: 70, label: "Resist Buffs"},
  {value: 71, label: "BST Pet Buffs"},
  {value: 72, label: "Summon Familiar"},
  {value: 73, label: "STR Buff"},
  {value: 74, label: "DEX Buff"},
  {value: 75, label: "AGI Buff"},
  {value: 76, label: "STA Buff"},
  {value: 77, label: "INT Buff"},
  {value: 78, label: "CHA Buff"},
  {value: 79, label: "Stat Debuffs"},
  {value: 80, label: "Invisible Undead"},
  {value: 81, label: "Invisible Animals"},
  {value: 82, label: "Invisibility"},
  {value: 83, label: "Absorb Damage"},
  {value: 84, label: "Casting Level Buffs"},
  {value: 85, label: "Clarity Line"},
  {value: 86, label: "Max Mana Buffs"},
  {value: 87, label: "Drain Mana"},
  {value: 88, label: "Mana Transfer"},
  {value: 89, label: "Instant Gain Mana"},
  {value: 90, label: "Lower Hate [Jolt]"},
  {value: 91, label: "Increase Archery"},
  {value: 92, label: "Attack Buff"},
  {value: 93, label: "Vision"},
  {value: 94, label: "Water Breathing"},
  {value: 95, label: "Improve Faction"},
  {value: 96, label: "Charm"},
  {value: 97, label: "Dispell"},
  {value: 98, label: "Lull"},
  {value: 99, label: "Mesmerise"},
  {value: 100, label: "Spell Focus Items"},
  {value: 101, label: "Snare [single]"},
  {value: 102, label: "Snare [Area of Effect]"},
  {value: 105, label: "Feign Death"},
  {value: 106, label: "Identify"},
  {value: 107, label: "Reclaim Energy"},
  {value: 108, label: "Find Corpse"},
  {value: 109, label: "Summon Player"},
  {value: 110, label: "Spell Shield"},
  {value: 112, label: "Blindness"},
  {value: 113, label: "Levitation"},
  {value: 114, label: "Extinguish Fatigue"},
  {value: 115, label: "Death Pact"},
  {value: 116, label: "Memory Blur"},
  {value: 118, label: "Height"},
  {value: 119, label: "Add Hate"},
  {value: 120, label: "Iron Maiden"},
  {value: 121, label: "Focus Spells"},
  {value: 122, label: "Melee Guard"},
  {value: 125, label: "Direct Damage [Fire]"},
  {value: 126, label: "Direct Damage [Ice]"},
  {value: 127, label: "Direct Damage [Poison]"},
  {value: 128, label: "Direct Damage [Disease]"},
  {value: 129, label: "Damage over Time [Fire]"},
  {value: 130, label: "Damage over Time [Ice]"},
  {value: 131, label: "Damage over Time [Poison]"},
  {value: 132, label: "Damage over Time [Disease]"},
  {value: 133, label: "INT Caster Chest Opening"},
  {value: 134, label: "INT Caster Chest Trap Appraisal"},
  {value: 135, label: "INT Caster Chest Trap Disarm"},
  {value: 136, label: "WIS Caster Chest Trap Disarm"},
  {value: 137, label: "WIS Caster Chest Trap Appraisal"},
  {value: 138, label: "WIS Caster Chest Opening"},
  {value: 140, label: "Destroy [Undead]"},
  {value: 141, label: "Destroy [Summoned]"},
  {value: 142, label: "Targeted Area of Effect [Fire]"},
  {value: 143, label: "Targeted Area of Effect [Ice]"},
  {value: 146, label: "Point Blank Area of Effect [Fire]"},
  {value: 147, label: "Point Blank Area of Effect [Ice]"},
  {value: 150, label: "Rain [Fire]"},
  {value: 151, label: "Rain [Ice]"},
  {value: 152, label: "Rain [Poison]"},
  {value: 154, label: "Fear Song"},
  {value: 155, label: "Fast Heals"},
  {value: 156, label: "Mana to Health"},
  {value: 157, label: "Pet Siphons"},
  {value: 159, label: "Cure [Disease]"},
  {value: 160, label: "Cure [Curse]"},
  {value: 161, label: "Cure [Multiple]"},
  {value: 162, label: "Cure [Blind]"},
  {value: 163, label: "Group Cure [Multiple]"},
  {value: 164, label: "Misc Effects"},
  {value: 165, label: "Shielding"},
  {value: 166, label: "PAL/RNG/BST Health Buffs"},
  {value: 167, label: "Symbols"},
  {value: 168, label: "Aegolism Line"},
  {value: 169, label: "Paladin AC Buffs"},
  {value: 170, label: "Spell Damage Mitigate"},
  {value: 171, label: "Spell/Melee Block"},
  {value: 172, label: "Spell Reflect"},
  {value: 173, label: "Hybrid AC Buffs"},
  {value: 174, label: "Health/Mana Regeneration"},
  {value: 175, label: "Aggro Decreasers"},
  {value: 200, label: "Misc Spells"},
  {value: 201, label: "Disciplines"},
  {value: 202, label: "Melee Haste"},
  {value: 203, label: "Area of Effect Slow"},
  {value: 204, label: "Summon Air Pet"},
  {value: 205, label: "Summon Water Pet"},
  {value: 206, label: "Summon Fire Pet"},
  {value: 207, label: "Summon Earth Pet"},
  {value: 208, label: "Summon Monster Pet"},
  {value: 209, label: "Transport [Antonica]"},
  {value: 210, label: "Transport [Odus]"},
  {value: 211, label: "Transport [Faydwer]"},
  {value: 212, label: "Transport [Kunark]"},
  {value: 213, label: "Transport [Velious]"},
  {value: 214, label: "Transport [Luclin]"},
  {value: 215, label: "Transport [Planes]"},
  {value: 216, label: "Transport [Gates/Omens]"},
  {value: 217, label: "Summon [Weapon]"},
  {value: 218, label: "Summon [Focus]"},
  {value: 219, label: "Summon [Food/Drink]"},
  {value: 220, label: "Summon [Armor]"},
  {value: 999, label: "AA/Abilities"}
];