export const SPELL_TARGET_TYPES = [
  {value: 0, label: "Rag'Zhezum Special"},
  {value: 1, label: "Line of Sight"},
  {value: 3, label: "Group V1"},
  {value: 4, label: "Point Blank Area of Effect"},
  {value: 5, label: "Single"},
  {value: 6, label: "Self"},
  {value: 8, label: "Targeted Area of Effect"},
  {value: 9, label: "Animal"},
  {value: 10, label: "Undead"},
  {value: 11, label: "Summoned"},
  {value: 13, label: "Life Tap"},
  {value: 14, label: "Pet"},
  {value: 15, label: "Corpse"},
  {value: 16, label: "Plant"},
  {value: 17, label: "Uber Giants"},
  {value: 18, label: "Uber Dragons"},
  {value: 20, label: "Targeted Area of Effect Life Tap"},
  {value: 24, label: "Area of Effect Undead"},
  {value: 25, label: "Area of Effect Summoned"},
  {value: 32, label: "Area of Effect Caster"},
  {value: 33, label: "NPC Hate List"},
  {value: 34, label: "Dungeon Object"},
  {value: 35, label: "Muramite"},
  {value: 36, label: "Area - PC Only"},
  {value: 37, label: "Area - NPC Only"},
  {value: 38, label: "Summoned Pet"},
  {value: 39, label: "Group No Pets"},
  {value: 40, label: "Area of EffectPC V2"},
  {value: 41, label: "Group v2"},
  {value: 42, label: "Self (Directional)"},
  {value: 43, label: "Group With Pets"},
  {value: 44, label: "Beam"}
];