/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2019-12-26 03:47:46 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c mysql://username:password@localhost/peq -t doors -s peq
 *
 */


export namespace doorsFields {
    export type id = number;
    export type doorid = number;
    export type zone = string | null;
    export type version = number;
    export type name = string;
    export type pos_y = number;
    export type pos_x = number;
    export type pos_z = number;
    export type heading = number;
    export type opentype = number;
    export type guild = number;
    export type lockpick = number;
    export type keyitem = number;
    export type nokeyring = boolean;
    export type triggerdoor = number;
    export type triggertype = number;
    export type disable_timer = boolean;
    export type doorisopen = number;
    export type door_param = number;
    export type dest_zone = string | null;
    export type dest_instance = number;
    export type dest_x = number | null;
    export type dest_y = number | null;
    export type dest_z = number | null;
    export type dest_heading = number | null;
    export type invert_state = number | null;
    export type incline = number | null;
    export type size = number;
    export type buffer = number | null;
    export type client_version_mask = number;
    export type is_ldon_door = number;

}

export interface IDoorData {
    id: doorsFields.id;
    doorid: doorsFields.doorid;
    zone: doorsFields.zone;
    version: doorsFields.version;
    name: doorsFields.name;
    pos_y: doorsFields.pos_y;
    pos_x: doorsFields.pos_x;
    pos_z: doorsFields.pos_z;
    heading: doorsFields.heading;
    opentype: doorsFields.opentype;
    guild: doorsFields.guild;
    lockpick: doorsFields.lockpick;
    keyitem: doorsFields.keyitem;
    nokeyring: doorsFields.nokeyring;
    triggerdoor: doorsFields.triggerdoor;
    triggertype: doorsFields.triggertype;
    disable_timer: doorsFields.disable_timer;
    doorisopen: doorsFields.doorisopen;
    door_param: doorsFields.door_param;
    dest_zone: doorsFields.dest_zone;
    dest_instance: doorsFields.dest_instance;
    dest_x: doorsFields.dest_x;
    dest_y: doorsFields.dest_y;
    dest_z: doorsFields.dest_z;
    dest_heading: doorsFields.dest_heading;
    invert_state: doorsFields.invert_state;
    incline: doorsFields.incline;
    size: doorsFields.size;
    buffer: doorsFields.buffer;
    client_version_mask: doorsFields.client_version_mask;
    is_ldon_door: doorsFields.is_ldon_door;

}
