/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2019-12-26 03:50:29 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c mysql://username:password@localhost/peq -t spawn2 -s peq
 *
 */


export namespace spawn2Fields {
    export type id = number;
    export type spawngroupID = number;
    export type zone = string | null;
    export type version = number;
    export type x = number;
    export type y = number;
    export type z = number;
    export type heading = number;
    export type respawntime = number;
    export type variance = number;
    export type pathgrid = number;
    export type _condition = number;
    export type cond_value = number;
    export type enabled = boolean;
    export type animation = boolean;

}

export interface ISpawn2DatabaseRow {
    id: spawn2Fields.id;
    spawngroupID: spawn2Fields.spawngroupID;
    zone: spawn2Fields.zone;
    version: spawn2Fields.version;
    x: spawn2Fields.x;
    y: spawn2Fields.y;
    z: spawn2Fields.z;
    heading: spawn2Fields.heading;
    respawntime: spawn2Fields.respawntime;
    variance: spawn2Fields.variance;
    pathgrid: spawn2Fields.pathgrid;
    _condition: spawn2Fields._condition;
    cond_value: spawn2Fields.cond_value;
    enabled: spawn2Fields.enabled;
    animation: spawn2Fields.animation;
}
