/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2019-12-26 20:30:40 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c mysql://username:password@localhost/peq -t spawngroup -s peq
 *
 */


export namespace spawngroupFields {
    export type id = number;
    export type name = string;
    export type spawn_limit = boolean;
    export type dist = number;
    export type max_x = number;
    export type min_x = number;
    export type max_y = number;
    export type min_y = number;
    export type delay = number;
    export type mindelay = number;
    export type despawn = boolean;
    export type despawn_timer = number;

}

export interface spawngroup {
    id: spawngroupFields.id;
    name: spawngroupFields.name;
    spawn_limit: spawngroupFields.spawn_limit;
    dist: spawngroupFields.dist;
    max_x: spawngroupFields.max_x;
    min_x: spawngroupFields.min_x;
    max_y: spawngroupFields.max_y;
    min_y: spawngroupFields.min_y;
    delay: spawngroupFields.delay;
    mindelay: spawngroupFields.mindelay;
    despawn: spawngroupFields.despawn;
    despawn_timer: spawngroupFields.despawn_timer;

}
