/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2019-12-26 03:41:49 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c mysql://username:password@localhost/peq -t zone -s peq
 *
 */


export namespace zoneFields {
    export type short_name = string | null;
    export type id = number;
    export type file_name = string | null;
    export type long_name = string;
    export type map_file_name = string | null;
    export type safe_x = number;
    export type safe_y = number;
    export type safe_z = number;
    export type graveyard_id = number;
    export type min_level = boolean;
    export type min_status = boolean;
    export type zoneidnumber = number;
    export type version = boolean;
    export type timezone = number;
    export type maxclients = number;
    export type ruleset = number;
    export type note = string | null;
    export type underworld = number;
    export type minclip = number;
    export type maxclip = number;
    export type fog_minclip = number;
    export type fog_maxclip = number;
    export type fog_blue = boolean;
    export type fog_red = boolean;
    export type fog_green = boolean;
    export type sky = boolean;
    export type ztype = boolean;
    export type zone_exp_multiplier = number;
    export type walkspeed = number;
    export type time_type = boolean;
    export type fog_red1 = boolean;
    export type fog_green1 = boolean;
    export type fog_blue1 = boolean;
    export type fog_minclip1 = number;
    export type fog_maxclip1 = number;
    export type fog_red2 = boolean;
    export type fog_green2 = boolean;
    export type fog_blue2 = boolean;
    export type fog_minclip2 = number;
    export type fog_maxclip2 = number;
    export type fog_red3 = boolean;
    export type fog_green3 = boolean;
    export type fog_blue3 = boolean;
    export type fog_minclip3 = number;
    export type fog_maxclip3 = number;
    export type fog_red4 = boolean;
    export type fog_green4 = boolean;
    export type fog_blue4 = boolean;
    export type fog_minclip4 = number;
    export type fog_maxclip4 = number;
    export type fog_density = number;
    export type flag_needed = string;
    export type canbind = boolean;
    export type cancombat = boolean;
    export type canlevitate = boolean;
    export type castoutdoor = boolean;
    export type hotzone = boolean;
    export type insttype = boolean;
    export type shutdowndelay = number;
    export type peqzone = boolean;
    export type expansion = boolean;
    export type suspendbuffs = boolean;
    export type rain_chance1 = number;
    export type rain_chance2 = number;
    export type rain_chance3 = number;
    export type rain_chance4 = number;
    export type rain_duration1 = number;
    export type rain_duration2 = number;
    export type rain_duration3 = number;
    export type rain_duration4 = number;
    export type snow_chance1 = number;
    export type snow_chance2 = number;
    export type snow_chance3 = number;
    export type snow_chance4 = number;
    export type snow_duration1 = number;
    export type snow_duration2 = number;
    export type snow_duration3 = number;
    export type snow_duration4 = number;
    export type gravity = number;
    export type type = number;
    export type skylock = boolean;
    export type fast_regen_hp = number;
    export type fast_regen_mana = number;
    export type fast_regen_endurance = number;
    export type npc_max_aggro_dist = number;
    export type max_movement_update_range = number;

}

export interface IZoneInfo {
    short_name: zoneFields.short_name;
    id: zoneFields.id;
    file_name: zoneFields.file_name;
    long_name: zoneFields.long_name;
    map_file_name: zoneFields.map_file_name;
    safe_x: zoneFields.safe_x;
    safe_y: zoneFields.safe_y;
    safe_z: zoneFields.safe_z;
    graveyard_id: zoneFields.graveyard_id;
    min_level: zoneFields.min_level;
    min_status: zoneFields.min_status;
    zoneidnumber: zoneFields.zoneidnumber;
    version: zoneFields.version;
    timezone: zoneFields.timezone;
    maxclients: zoneFields.maxclients;
    ruleset: zoneFields.ruleset;
    note: zoneFields.note;
    underworld: zoneFields.underworld;
    minclip: zoneFields.minclip;
    maxclip: zoneFields.maxclip;
    fog_minclip: zoneFields.fog_minclip;
    fog_maxclip: zoneFields.fog_maxclip;
    fog_blue: zoneFields.fog_blue;
    fog_red: zoneFields.fog_red;
    fog_green: zoneFields.fog_green;
    sky: zoneFields.sky;
    ztype: zoneFields.ztype;
    zone_exp_multiplier: zoneFields.zone_exp_multiplier;
    walkspeed: zoneFields.walkspeed;
    time_type: zoneFields.time_type;
    fog_red1: zoneFields.fog_red1;
    fog_green1: zoneFields.fog_green1;
    fog_blue1: zoneFields.fog_blue1;
    fog_minclip1: zoneFields.fog_minclip1;
    fog_maxclip1: zoneFields.fog_maxclip1;
    fog_red2: zoneFields.fog_red2;
    fog_green2: zoneFields.fog_green2;
    fog_blue2: zoneFields.fog_blue2;
    fog_minclip2: zoneFields.fog_minclip2;
    fog_maxclip2: zoneFields.fog_maxclip2;
    fog_red3: zoneFields.fog_red3;
    fog_green3: zoneFields.fog_green3;
    fog_blue3: zoneFields.fog_blue3;
    fog_minclip3: zoneFields.fog_minclip3;
    fog_maxclip3: zoneFields.fog_maxclip3;
    fog_red4: zoneFields.fog_red4;
    fog_green4: zoneFields.fog_green4;
    fog_blue4: zoneFields.fog_blue4;
    fog_minclip4: zoneFields.fog_minclip4;
    fog_maxclip4: zoneFields.fog_maxclip4;
    fog_density: zoneFields.fog_density;
    flag_needed: zoneFields.flag_needed;
    canbind: zoneFields.canbind;
    cancombat: zoneFields.cancombat;
    canlevitate: zoneFields.canlevitate;
    castoutdoor: zoneFields.castoutdoor;
    hotzone: zoneFields.hotzone;
    insttype: zoneFields.insttype;
    shutdowndelay: zoneFields.shutdowndelay;
    peqzone: zoneFields.peqzone;
    expansion: zoneFields.expansion;
    suspendbuffs: zoneFields.suspendbuffs;
    rain_chance1: zoneFields.rain_chance1;
    rain_chance2: zoneFields.rain_chance2;
    rain_chance3: zoneFields.rain_chance3;
    rain_chance4: zoneFields.rain_chance4;
    rain_duration1: zoneFields.rain_duration1;
    rain_duration2: zoneFields.rain_duration2;
    rain_duration3: zoneFields.rain_duration3;
    rain_duration4: zoneFields.rain_duration4;
    snow_chance1: zoneFields.snow_chance1;
    snow_chance2: zoneFields.snow_chance2;
    snow_chance3: zoneFields.snow_chance3;
    snow_chance4: zoneFields.snow_chance4;
    snow_duration1: zoneFields.snow_duration1;
    snow_duration2: zoneFields.snow_duration2;
    snow_duration3: zoneFields.snow_duration3;
    snow_duration4: zoneFields.snow_duration4;
    gravity: zoneFields.gravity;
    type: zoneFields.type;
    skylock: zoneFields.skylock;
    fast_regen_hp: zoneFields.fast_regen_hp;
    fast_regen_mana: zoneFields.fast_regen_mana;
    fast_regen_endurance: zoneFields.fast_regen_endurance;
    npc_max_aggro_dist: zoneFields.npc_max_aggro_dist;
    max_movement_update_range: zoneFields.max_movement_update_range;

}
